version: '3'
services:
  db:
    image: mysql:5.7 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat_system_development
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3300:3306"

  web:
    build: .
    working_dir: /chat_system_api
    volumes:
      - .:/chat_system_api
    command: bash -c "rm -f /chat_system_api/tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails server -b '0.0.0.0'"
    environment:
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch

  sidekiq:
    build: .
    command: bash -c "bundle install && bundle exec sidekiq"
    working_dir: /chat_system_api
    volumes:
      - .:/chat_system_api
    environment:
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db_data:
